INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01003','Soprole','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01004','Colún','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01005','Nestlé','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01006','Capel','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01007','Lactalis','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01008','Parmalat','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01009','Alpura','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01010','Danone','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01011','Dairy Farmers of America','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01012','Müller','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01013','Yoplait','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01014','Anchor','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01015','Milka','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01016','Arla','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01017','Lala','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01018','Borden','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01019','Fonterra','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01020','Fairlife','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01021','Clover','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01022','Dairylea','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01023','Valio','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01024','Meadow Fresh','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01025','Sodiaal','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01026','Lifeway','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01027','Agropur','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01028','Hiland Dairy','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01029','Tatura Milk Industries','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01030','Emmi','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01031','Lactel','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01032','Milkiland','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01033','Meadow Foods','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01034','Brookside Dairy Limited','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01035','DeLaval','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01036','Müller Milk & Ingredients','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01037','Meggle','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01038','Bulla Dairy Foods','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01039','Sütaş','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01040','FrieslandCampina','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01041','Mengniu Dairy','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01042','Bel Leerdammer','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01043','DFA Dairy Brands','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01044','Amul','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01045','Milk Link','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01046','Dairy Crest','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01047','Sodiaal Union','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01048','Royal FrieslandCampina','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01049','Milk Mantra','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01050','Megmilk Snow Brand','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01051','Schreiber Foods','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01052','Yakult','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01053','Dairygold','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01054','Bright Food','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01055','Fonterra Brands','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01056','Mother Dairy','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01057','Mengniu','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01058','Creamline Dairy Products','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01059','Bongrain','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01060','Grupo Lala','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01061','Tine','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01062','Schreiber','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01063','Ornua','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01064','Yili','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01065','Muller','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01066','Savencia','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01067','Meiji','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01068','Emmi Group','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01069','Müller Wiseman Dairies','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01070','Grupo Gloria','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01071','Yoplait Australia','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01072','Clover Industries','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01073','Meggle Group','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01074','Krafton Foods','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01075','Dairy Farmers','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01076','Weidendorf','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01077','The a2 Milk Company','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01078','Valley Milk','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01079','AmulFed Dairy','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01080','Lifeway Foods','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01081','PZ Cussons','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01082','Uelzena','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01083','McCain Foods','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01084','Clover SA','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01085','Dairy Farmers of Britain','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01086','First Milk','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01087','Meggle AG','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01088','Arla Foods Ingredients','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01089','Nestlé Dairy','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01090','Dean Foods','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01091','Müller UK & Ireland','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01092','Good Hope Dairy','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01093','Land O Lakes','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01094','Dairy Farmers Milk Co-operative','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01095','Laiteries Réunies','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01096','Parmalat Australia','B','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01097','Leprino Foods','C','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01098','Marigold Peel Fresh','D','No');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01099','Tatura Milk','A','Sí');
INSERT INTO proveedor(codigo,nombre,categoria,retencion) VALUES ('01100','Fair Cape Dairies','B','Sí');
