apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-deployment
  labels:
    app: proveedor-deployment
spec:
  selector:
    matchLabels:
      app: proveedor-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: proveedor-deployment
    spec:
      containers:
        - name: proveedor
          image: onicalls/proveedor-service
          ports:
            - containerPort: 8081
