apiVersion: v1
kind: Service
metadata:
  name: acopio-service
  namespace: milkstgo
  labels:
    app: acopio-service
spec:
  selector:
    app: acopio-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer