apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: milkstgo
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer