apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: milkstgo
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer