apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: milkstgo
  labels:
    app: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend
          image: onicalls/milkstgo-frontend
          ports:
            - containerPort: 3000
