apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
  labels:
    app: pago-deployment
spec:
  selector:
    matchLabels:
      app: pago-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pago-deployment
    spec:
      containers:
        - name: pago
          image: onicalls/pago-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db-service:3306/pago_db?autorReconnect=true&allowPublicKeyRetrieval=true&useSSL=false