apiVersion: v1
kind: Service
metadata:
  name: pago-service
  namespace: milkstgo
  labels:
    app: pago-service
spec:
  selector:
    app: pago-deployment
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: LoadBalancer