apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
  namespace: milkstgo
  labels:
    app: proveedor-service
spec:
  selector:
    app: proveedor-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer