apiVersion: v1
kind: Service
metadata:
  name: valorleche-service
  labels:
    app: valorleche-service
spec:
  selector:
    app: valorleche-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer