apiVersion: v1
kind: Service
metadata:
  name: valorleche-service
  namespace: milkstgo
  labels:
    app: valorleche-service
spec:
  selector:
    app: valorleche-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer