apiVersion: apps/v1
kind: Deployment
metadata:
  name: acopio-deployment
  labels:
    app: acopio-deployment
spec:
  selector:
    matchLabels:
      app: acopio-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: acopio-deployment
    spec:
      containers:
        - name: acopio
          image: onicalls/acopio-service
          ports:
            - containerPort: 8081
