apiVersion: apps/v1
kind: Deployment
metadata:
  name: valorleche-deployment
  labels:
    app: valorleche-deployment
spec:
  selector:
    matchLabels:
      app: valorleche-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: valorleche-deployment
    spec:
      containers:
        - name: valorleche
          image: onicalls/valorleche-service
          ports:
            - containerPort: 8081
